services:

  app:
    build:
      context: ./api/
      dockerfile: dockerfile
    container_name: lstm_app
    environment:
      - PYTHONUNBUFFERED=1
      - API_HOST=0.0.0.0
      - API_PORT=9010
    command: ["python", "-m", "src.main_api"]
    ports:
      - "9010:9010"
    volumes:
      - ./api/checkpoints:/app/checkpoints